name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - "v*"
    tags:
      - "*"

env:
  NODE_VERSION: 20

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package-location:
          - 'packages/ember-codemod-ember-render-helpers-to-v1'
          - 'packages/ember-render-helpers'
          - 'test-app'
    timeout-minutes: 5
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v5

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint
        working-directory: ${{ matrix.package-location }}

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package-location:
          - 'packages/ember-codemod-ember-render-helpers-to-v1'
          - 'packages/ember-render-helpers'
          - 'test-app'
    timeout-minutes: 5
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v5

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test
        working-directory: ${{ matrix.package-location }}

  get-test-matrix:
    name: Get test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-test-matrix.outputs.matrix }}
    timeout-minutes: 5
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v5

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: ${{ env.NODE_VERSION }}

      - id: set-test-matrix
        name: Set test matrix
        run: echo "matrix=$(pnpx @embroider/try list)" >> $GITHUB_OUTPUT
        working-directory: 'test-app'

  test-compatibility:
    name: Test compatibility
    needs: [get-test-matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-test-matrix.outputs.matrix) }}
    timeout-minutes: 5
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v5

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Make file changes
        run: pnpx @embroider/try apply ${{ matrix.name }}
        working-directory: 'test-app'

      - name: Install dependencies
        run: pnpm install --no-lockfile

      - name: Test
        env: ${{ matrix.env }}
        run: pnpm test
        working-directory: 'test-app'
